save_path: runs/test

# Enter components of the flow
flow: [0.1, 0]
$ flow: [x**2, y**2, z**2]

# Enter the boundary conditions for each coordinate as a python list
lower_boundaries: [0, 0]
upper_boundaries: [1, 1]
boundary_conditions: [periodic, periodic]

# Enter simulation parameters
num_particles: 200
time_step: 0.05
total_simulation_time: 10

# Enter dimensionless system parameters
st: 5
beta: 1
