name: pyplf
channels:
  - defaults
  - conda-forge
dependencies:
  - h5py>=3.14.0
  - matplotlib>=3.10.6
  - numpy>=2.3.3
  - pycodestyle>=2.14.0
  - python=3.13.7
  - pyyaml>=6.0.3
  - sympy>=1.14.0
  - ffmpeg>=6.1.1
